# Generated by Django 5.2 on 2025-04-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToken',
            new_name='AdminToken',
        ),
    ]
